name: Metrics
on:
  schedule:
    - cron: "0 16 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Metrics Left
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, 
          plugin_languages_skipped: lowlighter
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 5
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          output_action: pull-request
